#ifndef EXIT_CODES
#define EXIT_CODES

#define EXIT_WRONG_ARGUMENTS 1
#define EXIT_ERR_INIT_LIBNOTIFY 2
#define EXIT_ERR_DISK_STATUS_STAVFS 3
#define EXIT_LOG_FILE_ERROR 4
#define EXIT_CONFIG_FILE_NOT_FOUND 5

#endif // !EXIT_CODES
